version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: php-postgres14
    environment:
      POSTGRES_DB: term_db
      POSTGRES_USER: term_user
      POSTGRES_PASSWORD: qwe123
    networks:
      - php-network
    volumes:
      - postgres14_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    container_name: php-nginx
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - php-network
    volumes:
      - ./docker_conf/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker_conf/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./docker_conf/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker_conf/nginx/localhost.key:/etc/ssl/private/localhost.key
      - ./backend:/backend
      - ./frontend:/var/www/frontend
    depends_on:
      - php81
  php81:
    container_name: php-php81
    build: './docker_conf/php'
    expose:
      - 9003
    ports:
      - 9001:9001
    networks:
      - php-network
    volumes:
      - ./backend:/backend
      - ./docker_conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker_conf/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
    depends_on:
      - postgres

  redis:
    image: redis:6.2-alpine
    container_name: php-redis
    ports:
      - 6379:6379
    networks:
      - php-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: php-rabbitmq
    hostname: php-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 8081:15672
    networks:
      - php-network

  phppgadmin:
    container_name: pgadmin-front
    ports:
      - "8543:80"
    image: neimheadh/phppgadmin
    environment:
      POSTGRES_HOST: php-postgres14
      POSTGRES_PORT: 5432
      POSTGRES_DB: term_db
      POSTGRES_USER: term_user
      POSTGRES_PASSWORD: qwe123
    networks:
      - php-network
networks:
  php-network: null
volumes:
  postgres14_data: null
