version: "3"

services:  
  nginx:
    container_name: nginx-dev
    image: nginx:1.19.0-alpine
    ports:
      - 8090:80
    networks:
      - crm-network
    volumes:
      - ./frontend.conf:/etc/nginx/conf.d/frontend.conf
      - /Users/kpasek/Development/Crm/crm-app/dist:/var/www/frontend

networks:
  crm-network: