version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: php-postgres14
    environment:
      POSTGRES_DB: visit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    networks:
      - php-network
    volumes:
      - postgres14_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    container_name: php-nginx
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - php-network
    volumes:
      - ./docker_conf/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker_conf/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./docker_conf/nginx/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./docker_conf/nginx/nginx.key:/etc/ssl/private/nginx.key
      - ./docker_conf/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker_conf/nginx/localhost.key:/etc/ssl/private/localhost.key
      - /Users/kpasek/Development/php/backend:/backend
      - /Users/kpasek/Development/php/frontend:/var/www/frontend
  php81:
    container_name: php-php
    build: './docker_conf/php'
    expose:
      - 9003
    networks:
      - php-network
    volumes:
      - /Users/kpasek/Development/php/backend:/backend
      - /Users/kpasek/Development/docker/php/docker_conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  # rabbitmq:
  #   image: rabbitmq:3.9-management
  #   container_name: php-rabbitmq
  #   ports: 
  #     - 5672:15672
  #   networks:
  #     - php-network
  redis:
    image: redis:6.2-alpine
    container_name: php-redis
    ports:
      - 6379:6379
    networks:
      - php-network

networks:
  php-network:
volumes:
  postgres14_data:
