version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: php-postgres14
    environment:
      POSTGRES_DB: visit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    networks:
      - php-network
    volumes:
      - postgres14_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    container_name: php-nginx
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - php-network
    volumes:
      - ./docker_conf/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker_conf/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      # - ./docker_conf/nginx/nginx.crt:/etc/ssl/certs/nginx.crt
      # - ./docker_conf/nginx/nginx.key:/etc/ssl/private/nginx.key
      - ./docker_conf/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker_conf/nginx/localhost.key:/etc/ssl/private/localhost.key
      - /Users/kpasek/Development/php/backend:/backend
      - /Users/kpasek/Development/php/frontend:/var/www/frontend
  php81:
    container_name: php-php
    build: './docker_conf/php'
    expose:
      - 9003
    networks:
      - php-network
    volumes:
      - /Users/kpasek/Development/php/backend:/backend
      - /Users/kpasek/Development/docker/php/docker_conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  redis:
    image: redis:6.2-alpine
    container_name: php-redis
    ports:
      - 6379:6379
    networks:
      - php-network
  phppgadmin:
    restart: always
    container_name: php-pgadmin
    ports:
      - "8543:80"
    image: neimheadh/phppgadmin
    environment:
      POSTGRES_HOST: php-postgres14
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    networks:
      - php-network
  portainer:
    image: cr.portainer.io/portainer/portainer-ce:2.9.3
    restart: always
    container_name: php-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: php-redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    networks:
      - php-network

networks:
  php-network: null
volumes:
  postgres14_data: null
  portainer_data: null
  redisinsight: null
