version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: app-postgres14
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    networks:
      - app-network
    volumes:
      - postgres14_app:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    container_name: app-nginx
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - ./docker_conf/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker_conf/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker_conf/nginx/localhost.key:/etc/ssl/private/localhost.key
      - ./app:/var/www/app
    depends_on:
      - php81
  php81:
    container_name: app-php81
    build: './docker_conf/php'
    expose:
      - 9003
    ports:
      - 9001:9001
    networks:
      - app-network
    volumes:
      - ./app:/var/www/app
      - ./docker_conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker_conf/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
    depends_on:
      - postgres

  redis:
    image: redis:6.2-alpine
    container_name: app-redis
    ports:
      - 6379:6379
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: app-rabbitmq
    hostname: php-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - 8081:15672
    networks:
      - app-network

networks:
  app-network: null
volumes:
  postgres14_app: null
